services:
  # 1. BROKER MQTT (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # 2. NODE-RED 
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - ./nodered_data:/data
    depends_on:
      - mosquitto
      - influxdb
    dns:
      - 8.8.8.8
      - 1.1.1.1
  # 3. INFLUXDB - Baza danych szeregów czasowych (historia)
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=robotics_data
    volumes:
      - ./influxdb_data:/var/lib/influxdb

  # 4. GRAFANA - Wizualizacja
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3005:3000" # Port 3005, żeby nie gryzł się z Homepage
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=YOURPASSWORD
      - GF_AUTH_ANONYMOUS_ENABLED=true      # Włącza tryb anonimowy
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org. # Nazwa organizacji, dla której działa anonimowy dostęp (domyślnie 'Main Org')
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer   # Rola dla anonimowych użytkowników (Viewer = tylko podgląd)
      - GF_AUTH_ANONYMOUS_HIDE_UNBRANDING=true # Ukrywa logo Grafany w stopce (opcjonalnie)
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  # 5. SYMULATOR ROBOTA (OPC UA Server)

  virtual-robot:
    image: python:3.9-slim
    container_name: virtual-robot
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./robot_script:/app

    command: sh -c "pip install asyncua paho-mqtt && python robot_sim.py"

  vibration-worker:
    build: ./vibration-analysis  # Ścieżka do folderu z Dockerfile
    container_name: vibration-worker
    restart: unless-stopped
    environment:
      - MQTT_BROKER=mosquitto    # Nazwa kontenera brokera
      - INFLUX_URL=http://influxdb2:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=factory
      - INFLUX_BUCKET=sensors
    depends_on:
      - mosquitto
      - influxdb

# NOWY SERWIS: InfluxDB 2.x
  influxdb2:
    image: influxdb:2.7
    container_name: influxdb2
    ports:
      - "8087:8086"  # Na zewnątrz (przeglądarka) wchodzisz przez 8087
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=factory           # Twoja organizacja
      - DOCKER_INFLUXDB_INIT_BUCKET=sensors        # Twoje wiadro
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - influxdb2_data:/var/lib/influxdb2
    restart: unless-stopped
volumes:
  influxdb2_data: # Dodaj ten nowy na końcu pliku
